name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Containerized Build
      uses: ./.github/actions/redhat-build

    - name: Build musl
      run: |
        rustup target add x86_64-unknown-linux-musl 
        RUSTFLAGS='-C link-arg=-s' cargo build --release --target x86_64-unknown-linux-musl
        cp target/x86_64-unknown-linux-musl/release/displayMouse displayMouse-musl

    - name: Build gnu
      run: |
        rustup target add x86_64-unknown-linux-gnu 
        RUSTFLAGS='-C link-arg=-s' cargo build --release --target x86_64-unknown-linux-gnu
        # Copy the gnu binary to a different name for release generation
        cp target/x86_64-unknown-linux-gnu/release/displayMouse displayMouse-gnu

    - name: Run tests
      run: cargo test --verbose

    - name: Release
      uses: softprops/action-gh-release@v2
      if: github.ref_type == 'tag'
      with:
        generate_release_notes: true
        files: |
          Release.txt
          displayMouse-rh810
          displayMouse-musl
          displayMouse-gnu